export const ProjectData = [
  {
    index: 1,
    imgA: require("../../assets/languages/c-logo.svg"),
    imgB: require("../../assets/languages/icons8-react.svg"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqY?controls=0",
    CodPen: "",
    title: "Carbon Fiber Iron Man Helmet",
    summary: "C++ Arduino uno programming with custom machine application",
    github: "https://github.com/Rx8boi/GameRateSwap",
  },
  {
    index: 2,
    imgA: "",
    imgB: require("../../assets/languages/ruby.svg"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "Video Game Tracker CLI",
    summary: "Ruby based project with fetch calls",
  },
  {
    index: 3,
    imgB: require("../../assets/languages/ruby.svg"),
    imgA: require("../../assets/languages/sinatra.svg"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "Marvel Movie Project",
    summary: "Utilized Sinatra gem",
  },
  {
    index: 4,
    imgA: require("../../assets/languages/rails-1.svg"),
    imgB: require("../../assets/languages/html_css.png"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "GameRateSwap",
    summary:
      "GameRateSwap application that utilizes rails framework, omniauth gem & Devise.",
  },
  {
    index: 5,
    imgA: require("../../assets/languages/logo-javascript.svg"),
    imgB: require("../../assets/languages/html_css.png"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "My Fantasy League: NBA",
    summary:
      "Fantasy League for when you're ready for game time. NBA support with future NFL updates.",
  },
  {
    index: 6,
    imgA: require("../../assets/languages/angular.svg"),
    imgB: require("../../assets/languages/html_css.png"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "A Good Calculator",
    summary:
      "Simple calculator utilizing AngularJS, HTML5 & CSS. Showing junior level software engineering qualities.",
  },
  {
    index: 7,
    imgA: require("../../assets/languages/icons8-react.svg"),
    imgB: require("../../assets/languages/redux.svg"),
    imgC: "",
    imgD: "",
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    Github: "",
    CodPen: "",
    title: "TimeLine",
    summary:
      "TIme-Line application for Flatiron Final Project, utilizing ReactJs, Redux middleware, HTML5 & CSS",
  },
];
