export const ProjectData = [
  {
    index: 1,
    imgA: require("../../assets/languages/c-logo.svg"),
    imgB: require("../../assets/languages/arduino.svg"),
    imgC: require("../../assets/languages/Solid_white.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/VjzSb-KAFuc",
    CodPen: require("../../assets/languages/Solid_white.svg"),
    title: "Carbon Fiber Iron Man Helmet",
    summary:
      "My first venture into programming and the software engineering world. Creating a War Machine cosplay suit brought me to look into ways of automating the helmet & upon close, light up the LEDs in a specific way. When user pushes button to open faceplate, LEDs should turn off. This solution was solved with C++ Arduino uno programming and the helmet itself was created with carbon fiber & resin.",
    github: "",
    spec1: "Utilized C++ program w/ Arduino",
    spec2: "Integrated 2 Servos to open faceplate",
    spec3: "Integrated LEDs in series",
    spec4: "Integrated switch to begin program",
    spec5: "Applied to real-life concept",
  },
  {
    index: 2,
    imgA: require("../../assets/languages/ruby.svg"),
    imgB: require("../../assets/languages/Solid_white.svg"),
    imgC: require("../../assets/languages/Solid_white.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/pQKTdV-ldS0?start=75",
    github: "https://github.com/Rx8boi/videogame-cli",
    title: "Video Game Tracker CLI",
    summary:
      "Video Game Tracker CLI is a Ruby based project I created as part of the Flatiron curriculmn and was my real taste at software engineering. In this project along with familiarizing myself with ruby methods and basic OOP the application was my first attempt at web scrapping & fetch calls. Users can start the application and through interacting with commands see individual video games & their release dates. Other gems such as 'colorize' were used for styling",
    spec1: "Rails Framework",
    spec2: "MVC design & RESTful API",
    spec3: "Devise gem & custom views for user auth",
    spec4: "Omniauth gem for service log in/signup",
    spec5: "Boostrap for custom navigation bar",
  },
  {
    index: 3,
    imgA: require("../../assets/languages/ruby.svg"),
    imgB: require("../../assets/languages/sinatra.svg"),
    imgC: require("../../assets/languages/Solid_white.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/lBxg_WNawgE?start=43",
    github: "https://github.com/Rx8boi/sinatra-pro",
    title: "Marvel Movie Project",
    summary:
      "Utilizing Ruby's Sinatra gem, I created this project for all those that need to get started in the Marvel Cinematic Universe and would love to track their favorite (or all characters) journeys throughout the 10 year epic. It is here to help you chronologically follow the 20+ epic so far, journaling each character, each movie & plot twist along the way!",
    spec1: "Rails Framework",
    spec2: "MVC design & RESTful API",
    spec3: "Devise gem & custom views for user auth",
    spec4: "Omniauth gem for service log in/signup",
    spec5: "Boostrap for custom navigation bar",
  },
  {
    index: 4,
    imgA: require("../../assets/languages/rails-1.svg"),
    imgB: require("../../assets/languages/html5.svg"),
    imgC: require("../../assets/languages/css.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/T1WV5JS1e0k?start=20",
    github: "https://github.com/Rx8boi/GameRateSwap",
    title: "GameRateSwap",
    summary:
      "An app designed for users to add platforms & their games. Then rate those based upon the level of difficulty. This application utilizes ROR framework, omniauth gem & Devise. This was apart of my Flatiron Curriculm where I had to cover specific objectives. ",
    spec1: "Rails Framework",
    spec2: "MVC design & RESTful API",
    spec3: "Devise gem & custom views for user auth",
    spec4: "Omniauth gem for service log in/signup",
    spec5: "Boostrap for custom navigation bar",
  },
  {
    index: 5,
    imgA: require("../../assets/languages/logo-javascript.svg"),
    imgB: require("../../assets/languages/html5.svg"),
    imgC: require("../../assets/languages/css.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/WoswFHiY_Mo?start=51",
    github: "https://github.com/Rx8boi/GameRateSwap",
    title: "My Fantasy League: NBA",
    summary:
      "My Fantasy League: NBA is an application I designed for users to view teams & create/edit players to track. Users were able to interact with single paged application (SPA) & back-end API for full CRUD operations without page refresh. After initial functionality Bootstrap along with CSS to creat clean front-end look.",
    spec1: "Rails Framework",
    spec2: "MVC design & RESTful API",
    spec3: "Devise gem & custom views for user auth",
    spec4: "Omniauth gem for service log in/signup",
    spec5: "Boostrap for custom navigation bar",
  },
  {
    index: 6,
    imgA: require("../../assets/languages/angular.svg"),
    imgB: require("../../assets/languages/html5.svg"),
    imgC: require("../../assets/languages/css.svg"),
    imgD: require("../../assets/languages/Solid_white.svg"),
    Vid: "https://www.youtube.com/embed/tgbNymZ7vqYcontrols=0",
    github: "https://github.com/Rx8boi/GameRateSwap",
    CodPen: require("../../assets/languages/Solid_white.svg"),
    title: "A Good Calculator",
    summary:
      "Simple calculator utilizing AngularJS, HTML5 & CSS. Showing junior level software engineering qualities.",
    spec1: "Rails Framework",
    spec2: "MVC design & RESTful API",
    spec3: "Devise gem & custom views for user auth",
    spec4: "Omniauth gem for service log in/signup",
    spec5: "Boostrap for custom navigation bar",
  },
  {
    index: 7,
    imgA: require("../../assets/languages/icons8-react.svg"),
    imgB: require("../../assets/languages/redux.svg"),
    imgC: require("../../assets/languages/html5.svg"),
    imgD: require("../../assets/languages/css.svg"),
    Vid: "https://www.youtube.com/embed/zzSF94QW1Wk?start=22",
    github: "https://github.com/Rx8boi/Timeline",
    title: "TimeLine",
    summary:
      "A single page application utilizing a vertical timeline for my Flatiron Final Project. Project was basis for portfolio project & user could add/delete Timeline entries as well as utilize state to increase the 'like counter' on each timeline card.",
    spec1: "ReactJs w/ Redux Middleware",
    spec2: "Created with react-router",
    spec3: "Rails API",
    spec4: "Multiple Routes",
    spec5: "Utilized functional & Class components",
  },
];
